import Footer from "@/components/footer";
import type { Metadata } from "next";
import { Inter, Sora } from "next/font/google";
import localFont from "next/font/local";
import Link from "next/link";
import { MdCallMade } from "react-icons/md";
import "./globals.css";

const soraSans = Sora({
  variable: "--font-sora-sans",
  subsets: ["latin"],
});
const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const coolvetica = localFont({
  variable: "--font-coolvetiva",
  src: "../public/Coolvetica.otf",
});

const nyghtSerif = localFont({
  variable: "--font-nyght-serif",
  src: "../public/NyghtSerif.otf",
});

export const metadata: Metadata = {
  title: "Estúdio Giomo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${soraSans.variable} ${interSans.variable} ${coolvetica.variable} ${nyghtSerif.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 flex justify-between items-center bg-white w-full mx-auto max-w-7xl px-5 py-4">
          <Link href={"/"}>
            <h1 className="font-sans text-xl font-bold tracking-tighter">
              Estúdio Giomo
            </h1>
          </Link>
          <Link href={"/"}>
            <span className="flex items-center gap-1 group">
              <h3 className="font-inter text-base font-medium group-hover:underline">
                Entre em contato
              </h3>
              <MdCallMade />
            </span>
          </Link>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
